### PR TITLE
use system temp dir

### PR DESCRIPTION
**Pull request by notoriaga**
Found a race condition where temp files weren't cleaned up quick enough after a download and some other code that walked the download dir picked up the temp files. This uses the system temp dir instead of the pwd. This also means that should some code panic (or you ctrl-c the bin) the files will still be cleaned up (because the os handles the cleanup now)

### CODE REVIEW

**Comment by samvrlewis** [comment]
Annoyingly `tempfile` has the caveat ["Note: Temporary files cannot be persisted across filesystems."](https://docs.rs/tempfile/latest/tempfile/struct.TempPath.html#method.persist) which is why we chose the `tempfile_in` approach at the time (at the time on CI `/tmp/` was on a different (tmpfs? I think) filesystem so this made the integration tests fail). 

Had a little look and it looks like this is because tempfile uses the `rename` system call https://github.com/Stebalien/tempfile/blob/1a40687e06eb656044e3d2dffa1379f04b3ef3fd/src/file/imp/unix.rs#L131 which doesn't work across filesystems (https://man7.org/linux/man-pages/man2/rename.2.html) - apparently because copying the data is something that should happen in userspace. I wonder if we could/should submit a PR to tempfile to allow persisting via copying/deleting rather than renaming? Otherwise I'm not sure this will be doable as I think it'll stop esthri from being able to download on systems that have `/tmp` tmpfs backed.

**Comment by notoriaga** [comment]
Ahh dang, I knew it couldn't be that easy. I have a fix for this for my use case so it's no big deal, but yeah maybe we can figure something out

**Comment by notoriaga** [comment]
Another way around this might be to make the tmp dir configurable? Maybe something like 

```
ESTHRI_TEMP_DIR=system // what I have here
ESTHRI_TEMP_DIR=dest // what we have now
ESTHRI_TEMP_DIR=/an/actual/path // use that path
``` 

but I also think a contribution to tempfile would be nice

**Comment by silverjam** [comment]
Making things configurable sounds reasonable, I think our ctrl-c handler and panic handler could be improved to clean-up these files too.  I think `rename` is typically used because the operation is atomic at the OS level, other methods are not atomic so you are more likely to have in-between states where things can be half moved.

**Comment by notoriaga** [comment]
closing in favor of https://github.com/swift-nav/esthri/pull/285

**Pull request closed without merging**
